# Configuration for classifier


classifier:
  # Model confuration
  model:
    # Model task
    task: classify

    # Model weight path
    weight: weights/uniform.pt

    # Confidence threshold for detection
    conf: 0.8

    # Intersection over Union
    iou: 0.4

    # Input size for the model
    size: 480

    # Use half precision (float16) for better inference
    half: true

    # Fuse model layer
    fuse: false

    # Using onnx model
    onnx: false

    # Use TorchDynamo, the latest method to speed up PyTorch code
    optimize: false

    # Backend to be used for model optimization
    backend: null

  # Draw output
  show:
    # Detection confidence score
    score: false

    # Show dynamic color based on score
    dynamic_color: true

    # Box surrounding
    text: true

  # Save result
  save: true
